#!/bin/bash
# generate_inventory.sh - Genera inventory.ini automáticamente usando outputs de Terraform
# Uso: ./generate_inventory.sh /ruta/al/terraform/infra

set -e

if [ -z "$1" ]; then
  echo "Uso: $0 /ruta/al/terraform/infra"
  exit 1
fi

TF_DIR="$1"
cd "$TF_DIR"

# Obtener outputs de Terraform en JSON
tfout=$(terraform output -json)

# Extraer valores necesarios
VM_PUBLIC_IP=$(echo "$tfout" | jq -r '.vm_public_ip.value')
MYSQL_VM_PRIVATE_IP=$(echo "$tfout" | jq -r '.mysql_vm_private_ip.value')

# Volver al directorio original
cd - > /dev/null

# Generar inventory.ini
cat > inventory.ini <<EOF
# Ansible Inventory for Azure Gitea
# Auto-generated by generate_inventory.sh

[azureGitea]
vm-instance ansible_host=$VM_PUBLIC_IP ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/azure-gitea-key.pem

[azureGitea:vars]
# MySQL VM connection details (from Terraform outputs)
mysql_host=$MYSQL_VM_PRIVATE_IP

[mysql-replica]
mysql-replica-vm ansible_host=$MYSQL_VM_PRIVATE_IP ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/azure-gitea-key.pem

[mysql-replica:vars]
# mysql_root_password is passed via --extra-vars from Jenkins for security
gitea_replica_user=gitea_replica
gitea_replica_password=ChangeThisReplicaPassword!
gitea_replica_db=gitea_replica_db
mysql_server_id=2
EOF

echo "✅ Archivo inventory.ini generado correctamente."
echo "⚠️  IMPORTANTE: Pasa mysql_root_password via --extra-vars al ejecutar el playbook:"
echo "   ansible-playbook -i inventory.ini playbook.yml --extra-vars 'mysql_root_password=YOUR_PASSWORD'"
